preset: recommended

risky: false

linting: true

enabled:
  - long_array_syntax
  - unalign_double_arrow

disabled:
  - align_double_arrow

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-contains:
    - "config"
  depth:
    - "< 3"
