language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=stable

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi

script: vendor/bin/phpunit
